### ISSUE TITLE
iPhone 14 poor tracking issue

### ISSUE THREAD

**Issue by XkRecarens** [StandardCyborg/StandardCyborgSDK#9] opened 2023-04-06 13:25 UTC
I recently started testing the iPhone 14 to scan and the results are much worse than on previous iPhones. When you scan 360º the object normally starts to shake and moves, I understand that it is due to loss of tracking. Does anyone have an idea how to solve the problem?

**Comment by aaptho** [comment] 2023-04-10 04:12
Duplicate of https://github.com/StandardCyborg/StandardCyborgCocoa/issues/32

**Closed as not planned by aaptho** 2023-04-10 04:12 UTC
